# Generated by Django 2.1.5 on 2019-02-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=0, help_text='Designates that this user can post new articles.', verbose_name='author status'),
        ),
    ]
